### ISSUE TITLE
Russian Language

### ISSUE THREAD

**Issue by sovaby** [brianhornsby/plugin.audio.tuneinradio#100]
When you chane the locale to ru_RU then the menu in the first window is ok but in the Category
shows nothing and still black lines without words
only Live TV .

**Comment by vlmaksime** [comment]
Добавил поддержку русского языка. Пока изменения не внесли в текущий репозитарий, можете установить версию аддона с поддержкой русского отсюда:
https://github.com/vlmaksime/plugin.audio.tuneinradio/releases/tag/v3.0.0_ru

**Comment by brianhornsby** [comment]
Unable to reproduce using latest development branch.
