### ISSUE TITLE
Not able to scrobble to last.fm ?

### ISSUE THREAD

**Issue by gordielachance** [brianhornsby/plugin.audio.tuneinradio#101]
Hi and thanks you for your addon, I love it !

Well, there is something I miss : 

Why does it not scrobble to last.fm ?

I have the official last.fm enabled and the option 'Submit streaming radio to Last.fm' checked.
Scrobbling works with other plugins like the [Subsonic addon](https://github.com/gordielachance/plugin.audio.subsonic), so I guess this is an addon problem rather than a Kodi problem.

Any ideas ?
Thanks !

**Comment by brianhornsby** [comment]
The add-on plays one continuous stream of music, not individual tracks, so I do not believe it is possible to scrobble to last.fm.
