### ISSUE TITLE
RadioTime API Methods: Describe fails on Custom urls

### ISSUE THREAD

**Issue by lordbarba** [brianhornsby/plugin.audio.tuneinradio#106]
Hi, 
i'm trying to run run the Describe command, passing the ID of a custom url but empty answer.

This is my custom url retrieved by Browse:
<outline type="link" text="Manual_BBC1" URL="http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p" guide_id="u6" item="url" image="http://cdn-radiotime-logos.tunein.com/s0q.png" preset_number="65" preset_id="u6" is_preset="true"/>

This is the describe command: 

    http://opml.radiotime.com/Describe.ashx?id=u6&partnerId=>partner_id>&username=<username>

And this is the answer:

    <opml version="1">
    <head>
    <status>200</status>
    </head>
    <body></body>
    </opml>

Any ideas?
Thanks
Leo

**Comment by brianhornsby** [comment]
As far as I'm aware you can not describe a custom url using the TuneIn API
https://github.com/brianhornsby/plugin.audio.tuneinradio/wiki/RadioTime-API-Methods:-Describe
