### ISSUE TITLE
Error on getting Favorites

### ISSUE THREAD

**Issue by hencou** [brianhornsby/plugin.audio.tuneinradio#115]
Thanks for your great work!

Found a problem in Favorites in the latest 3.0 development version:
When I click on Favorites, Kodi gives an error.
When I change __partnerid__ = 'yvcOjvJP' to __partnerid__ = 'RadioTime' in "default.py" the Favorites are working again.

**Comment by brianhornsby** [comment]
Duplicate of issue #111, so closing issue.
