### ISSUE TITLE
Failing to play 181.FM (2.0.5 develop)

### ISSUE THREAD

**Issue by coelhopsi** [brianhornsby/plugin.audio.tuneinradio#51]
Hi Brian,

The add-on is failing when trying to play any station under 181.FM. Looks like a similar issue as the one reported on issue #43, however, on this case, there is one more PLS level, so there would need to be a third pass to parse it.

Debug Log: http://www.xbmclogs.com/show.php?id=200950

---

18:37:06 T:3036786688   DEBUG: CCurlFile::GetMimeType - http://www.181.fm/tunein.pls?station=181-uktop40&style=mp3&description=UK%20top%2040 -> audio/x-scpls
18:37:06 T:3036786688   ERROR: Playlist Player: skipping unplayable item: 6, path [plugin://plugin.audio.tuneinradio/?logo=http%3A%2F%2Fd1i6vahw24eb07.cloudfront.net%2Fs126794q.png&path=tune&id=s126794&name=181.FM+UK+Top+40]

---

Would there be a way to implement a loop instead of additional passes? It would then loop until no more PLSs remain... not sure if this is the best way to have this fixed, though...

**Comment by brianhornsby** [comment]
Unable to reproduce in latest development branch.
