### ISSUE TITLE
No Antenne Bayern with update 2.0.1.1

### ISSUE THREAD

**Issue by fgerrits** [brianhornsby/plugin.audio.tuneinradio#62]
Upgraded from version 2.0.5 to 2.0.1.1 and the recents and search options show Antenne Bayern, but none of them is playing anymore :(
Could that be fixed ?

Very nice plugin btw :P

Greatz.

**Comment by fgerrits** [comment]
Oke thankx for your reply, try that fix.. im not yet over to kodi, still running minix xbmc 13.3

**Comment by brianhornsby** [comment]
Issue is both on Kodi (14) and XBMC (13).
