### ISSUE TITLE
Plugin fails to install on Kodi 14.1 (Helix)

### ISSUE THREAD

**Issue by msibbald** [brianhornsby/plugin.audio.tuneinradio#64]
Logs
http://xbmclogs.com/show.php?id=409751

**Comment by brianhornsby** [comment]
You are installing the plugin using the SuperRepo repository, which is using an old version (2.0.5). 
I have nothing to do with that repository and I don't supply my own repository.
Install the plugin using the ZIP file.
https://github.com/brianhornsby/plugin.audio.tuneinradio/releases/download/v2.1.0/plugin.audio.tuneinradio-2.1.0.zip
