### ISSUE TITLE
force streaming format per radio station

### ISSUE THREAD

**Issue by ed76** [brianhornsby/plugin.audio.tuneinradio#65]
would it be possible to add posibiltity to force a streamingfomat per channel/station? i have aac and mp3 radio stations. some station have 64 kb aac and 320kb mp3 quality but kodi tunein plugin chooses the lower quality 64kb aac. if i could force "mp3" only for that station tunin would play @320kb mp3. i tested this with global format setting and this works (but than aac only stations didnt work)

**Comment by ed76** [comment]
if the suggestion above should not be possible, maybe its possible that tunein kodi addon will have a more "intelligent" choise about what stream is used. at the moment it seems aac is prefered over mp3. but the bitrat is more more important. mp3@320kb has defenitively a better soundquality than acc@64kb.

**Comment by brianhornsby** [comment]
Hi,

What you are suggesting in the first post is possible. The plugin can be changed to allow a user to select a particular stream.
Unfortunately, at the moment I'm a bit busy in my personal and professional life, so not sure when I'll be able to get a new version of the plugin released.

Regards

Brian

**Comment by ed76** [comment]
i will wait. thanks a lot!

**Comment by brianhornsby** [comment]
Raised issue #76
