### ISSUE TITLE
Tunein won't install

### ISSUE THREAD

**Issue by redo109** [brianhornsby/plugin.audio.tuneinradio#66]
I added the repository Gotham and found Tunein clicked to install. The installation starts and the download gets to around 85 to 99% and I get working onscreen then nothing has changed the add on is not there. I added BBC podcast and that worked fine. Just wondered if this is a temporary glitch t the server or something I'm doing wrong? 
Running Raspberry PI b with 512mbRAM and latest build of Raspbmc.
Richard

**Comment by brianhornsby** [comment]
I don't have a repository. So nothing to do with me.
Use the release zip [file](https://github.com/brianhornsby/plugin.audio.tuneinradio/releases/download/v2.1.0/plugin.audio.tuneinradio-2.1.0.zip) to install.

**Comment by redo109** [comment]
Many thanks loaded now
