### ISSUE TITLE
Cannot play a mp3 Radio (special character ?) 

### ISSUE THREAD

**Issue by freechelmi** [brianhornsby/plugin.audio.tuneinradio#69]
Hi , all of the radios I've tried worked except for this one : 

```
<outline type="audio" text="Radio Galère" URL="http://opml.radiotime.com/Tune.ashx?id=s50525" bitrate="128" reliability="100" guide_id="s50525" subtext="L'association GALERE se..." genre_id="g88" formats="mp3" item="station" image="http://cdn-radiotime-logos.tunein.com/s50525q.png" now_playing_id="s50525" preset_id="s50525"/>
```

Can it be because of the è in the text attribute?

this station works great in the website or tuneinapp

**Comment by brianhornsby** [comment]
Plays ok on my OpenELEC and OSX versions of Kodi.
Make sure you have the latest version of the [add-on](https://github.com/brianhornsby/plugin.audio.tuneinradio/releases/download/v3.0.0/plugin.audio.tuneinradio-3.0.0.zip) or my [repository](https://github.com/brianhornsby/repository.brianhornsby/releases/download/v1.0.0/repository.brianhornsby-1.0.0.zip).
