### ISSUE TITLE
V2.1.0 some stations not supported

### ISSUE THREAD

**Issue by paulbl** [brianhornsby/plugin.audio.tuneinradio#70]
Hi
Using Smart Phone or browser Jacaranda radio plays fine but using plugin on Kodi it says unsupported and script error when tried.
Why would it play everywhere but on Kodi?
Is there a way around this that I can use or is someone working on it.
Thanks

**Comment by davisstu** [comment]
This is the same for Absolute Radio 90s. Strangely, all the other Absolute stations play fine. In fact, I can't recall AR90s ever working on this plugin.

**Comment by brianhornsby** [comment]
Kodi only play's certain formats and doesn't play external web based radio streams.
No fix.
