### ISSUE TITLE
Kodi 15 beta 2 displays song text incorrectly...

### ISSUE THREAD

**Issue by gslender** [brianhornsby/plugin.audio.tuneinradio#71]
This could be a Kodi 15 thing, or perhaps something changed in the way Kodi works (API wise) but the song/station text is now all wrong with the XML or url text showing when it should just show the song titles etc.

Might be worth looking at to just confirm the API hasn't changed (among other things).

G

**Comment by brianhornsby** [comment]
I don't set the song title when playing a station.
The station name seems to be displayed correctly on my OpenELEC and OSX Kodi 15 installs.
