### ISSUE TITLE
Kodi - add-on does not have correct structure

### ISSUE THREAD

**Issue by GrahamGIGA** [brianhornsby/plugin.audio.tuneinradio#72]
I have downloaded the latest version and (I think) checked that it is correct, but when trying to install from zip on Kodi on Slice, I keep getting the above error.

Any help would be most welcome

**Comment by brianhornsby** [comment]
Did you get the file from https://github.com/brianhornsby/plugin.audio.tuneinradio/releases/download/v2.1.0/plugin.audio.tuneinradio-2.1.0.zip

**Comment by GrahamGIGA** [comment]
I downloaded via the 'download zip' button in this project.

Cheers
