### ISSUE TITLE
Tunein Radio plugin zip file downloaded & installed but not working 

### ISSUE THREAD

**Issue by phk1611** [brianhornsby/plugin.audio.tuneinradio#77]
I tried Installing tunein radio Plugin - plugin.audio.tuneinradio-master.zip 
& latest plugin.audio.tuneinradio-2.1.0.zip,
Installed on kodi 15 but the addon of tunein doesnot, show library to browse for radio stations.
After clicking Tunein addon the wizard shows (direct page) only certain radio station , 
how can this be fixed. The Radio station library doesn't load.
![kodi - tunein addon](https://cloud.githubusercontent.com/assets/15387256/10833106/a225852e-7eb5-11e5-80f2-9a81451675bd.png)
![tunein addon direct page](https://cloud.githubusercontent.com/assets/15387256/10833121/bda3b9e2-7eb5-11e5-8741-c135beb23ed5.png)

**Comment by brianhornsby** [comment]
Don't use whatever that TVAddons wizard thing is.
Install it from the zip.
https://github.com/brianhornsby/plugin.audio.tuneinradio/releases/download/v3.0.0/plugin.audio.tuneinradio-3.0.0.zip
Then go to Add-ons and launch it.

**Comment by phk1611** [comment]
Uninstalled older plugin, and installed pugin from suggested link https://github.com/brianhornsby/plugin.audio.tuneinradio/releases/download/v3.0.0/plugin.audio.tuneinradio-3.0.0.zip 
But, same situation,

**Comment by phk1611** [comment]
![tunein addon direct station](https://cloud.githubusercontent.com/assets/15387256/10834227/991646dc-7ebd-11e5-9b86-65a2352d45da.png)
Only this stations are available.
Tunein search page doesn't load instead the addon directs to following page.
![tunein addon direct page](https://cloud.githubusercontent.com/assets/15387256/10834295/37af2bce-7ebe-11e5-86f7-e48991bc1918.png)

**Comment by brianhornsby** [comment]
You appear to be running in File mode. Run in Library mode.

**Comment by phk1611** [comment]
how to navigate to library mode, the option of library at the left side panel doen't work.

**Comment by phk1611** [comment]
library option on left panel don't activate

**Comment by brianhornsby** [comment]
Have you added a source and added music/movies to you library,
http://kodi.wiki/view/Adding_music_to_the_library

**Comment by learninggrowing** [comment]
I use Allavsoft to download music from Spotify, Deezer, Tunein etc

**Comment by brianhornsby** [comment]
Setup issue. Not an issue with the plugin.
