### ISSUE TITLE
Metada outdated

### ISSUE THREAD

**Issue by riotbr** [brianhornsby/plugin.audio.tuneinradio#85]
I've noticed that the metadata information it's outdated for 2 or 3 days. It's happening with any radio.

Specs:
- OpenELEC 5.0.8 (32 bits);
- Kodi 14.1;
- Tunein addon 3.0.0.

I tried to solve this reinstalling the addon but the problem is persistent.

This is happening on Kodi 16.0 too (running on a Windows 7 Ultimate 64 bits).

It's just with me?

**Comment by brianhornsby** [comment]
Unable to reproduce in latest development build
