### ISSUE TITLE
Greek language not working

### ISSUE THREAD

**Issue by bugatsinho** [brianhornsby/plugin.audio.tuneinradio#92]
When you chane the locale to el_GR then the menu in the first window is ok but in the second window shows nothing and still black lines without greek words

**Comment by sovaby** [comment]
Same you chane the locale to ru_RU then the menu in the first window is ok but in the Category
shows nothing and still black lines without words
only Live TV .

**Comment by brianhornsby** [comment]
Unable to reproduce on latest development branch
