### ISSUE TITLE
ALWAYS REQUEST

### ISSUE THREAD

**Issue by calaiou** [brianhornsby/plugin.audio.tuneinradio#93]
WHEN I CHANGE RADIO ALWAYS REQUEST:
"YOU WANT PLAY A FLUX"
  ANOTHER ADDON FOR EXEMPL "RADIO" DONT TELL ME THIS
SORRY FOR MY ENGLISH AND MUCH RESPECT

**Comment by brianhornsby** [comment]
Disable the 'Prompt When Changing Station' setting in the 'Appearance' tab in the add-on settings.
