### ISSUE TITLE
Allow Users to Edit Station and Show Names inside "Favorites" folder

### ISSUE THREAD

**Issue by wstephen** [brianhornsby/plugin.audio.tuneinradio#96]
This Addon has a powerful feature to search, and in fact, discovers many interesting contents.  Of cause, it is in users' interest to save them.  These names are, often, too brief, incomplete to give an impression of what they actually are, and in particular, when there are many of them inside the "favorites".

I strongly suggest an improvement to allow users to edit those names in their own language.  If it is workable, allow categorization by users as well.

Thanks!

**Comment by Smeulf** [comment]
Hi, your request looks like the same as https://github.com/brianhornsby/plugin.audio.tuneinradio/issues/50, closes since 2 years 'cause the add-on is 'just' retreiving data from the tunein api.

Cheers.

Smeulf

**Comment by brianhornsby** [comment]
This is not possible as TuneIn API does not allow it.
