### ISSUE TITLE
Playlist - Can't find next item to play

### ISSUE THREAD

**Issue by HighTech1972** [brianhornsby/plugin.audio.tuneinradio#97]
While choosing Kiss 92.5 station to play, I am getting "Playlist - Can't find next item to play"
This station plays perfectly on the Tunein android app and also using other Radio add-ons

**Comment by ltoolio** [comment]
Same issue here on a different station (93XRT in Chicago)

From what I've read on other issues, it might have to do with how the station is streaming via the site you listen to them on.

I've been trying to find the source stream URL in my case with no success.  Maybe you'll have better luck.

**Comment by igotu2** [comment]
Yeah I'm having the same issues on a few of my stations too I think add on just might need to be updated the stations work fine on tunein radio app on iPhone

**Comment by brianhornsby** [comment]
As @ltoolio says the problem is with the stream being returned by TuneIn, either Kodi can not play it or its a URL to an external website.
